apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: prasanna-loop-helm
  namespace: argo
spec:
  entrypoint: deploy-helm-chart
  templates:
    - name: deploy-helm-chart
      dag:
        tasks:
          - name: helm-install
            template: helm-install
  # Define the Helm install template
    - name: helm-install
      inputs:
        parameters:
          - name: chart-name
            value: hello-world
          - name: chart-version
            value: 0.1.0
      container:
        image: dtzar/helm-kubectl
        command: [helm]
        args:
          - install
          - my-hello-world-chart
          - /root/hello-world-chart/hello-world-0.1.0.tgz

