apiVersion: batch/v1
kind: Job
metadata:
  labels:
    workflows.argoproj.io/controller-instanceid: ml-argo
  name: prasanna-loop-helm-preinstall
  namespace: ml-eng-team
spec:
  template:
    spec:
      containers:
        - name: helm-hook
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args: ["wget -O - https://raw.githubusercontent.com/your-repo/script.sh | sh"]
      restartPolicy: Never
  backoffLimit: 0
